Repository 2025-AI-Seoul-Hackathon-Leafstorm/Frontend, pull requests merged in 2025-04, with the labels that each got.

#15 Feat: simply add errorPage, noteFoundPage #14
  src/app/error.jsx
  src/app/not-found.jsx
Labels: enhancement, feat

#16 Feat#13/file selection page
  next.config.ts
  package-lock.json
  package.json
  src/app/files/detail/page.jsx
  src/app/files/page.jsx
  src/components/screen/DocList.jsx
  src/components/screen/MarkdownPreview.tsx
  src/components/ui/ActionButton.jsx
  src/components/ui/DropdownItem.jsx
  src/components/ui/DropdownMenu.jsx
  src/components/ui/FileHandleMenuBar.jsx
  src/components/ui/TagBadge.jsx
Labels: enhancement, feat

#18 Ref. PR Develop for connect pages
  next.config.ts
  package-lock.json
  package.json
  src/app/error.jsx
  src/app/files/detail/page.jsx
  src/app/files/page.jsx
  src/app/not-found.jsx
  src/components/screen/DocList.jsx
  src/components/screen/MarkdownPreview.tsx
  src/components/ui/ActionButton.jsx
  src/components/ui/DropdownItem.jsx
  src/components/ui/DropdownMenu.jsx
  src/components/ui/FileHandleMenuBar.jsx
  src/components/ui/TagBadge.jsx
Labels: enhancement, feat

#22 feat: add ChatbotModal file and detail2 file #22
  src/app/files/detail2/page.jsx
  src/components/ui/ChatBubble.jsx
  src/components/ui/ChatbotModal.jsx
  src/components/ui/DetailModal.jsx
Labels: enhancement, feat

#24 Update: get develop file to work on API
  src/app/files/detail2/page.jsx
  src/components/ui/ChatBubble.jsx
  src/components/ui/ChatbotModal.jsx
  src/components/ui/DetailModal.jsx
Labels: enhancement, Refactoring

#25 Update Header.tsx
  src/components/common/Header.tsx
Labels: enhancement

#26 Update fileUtils.ts
  src/utils/fileUtils.ts
Labels: enhancement

#27 Chore: update typscript errors
  src/app/files/detail2/page.jsx
  src/components/common/Header.tsx
  src/components/ui/ChatBubble.jsx
  src/components/ui/ChatbotModal.jsx
  src/components/ui/DetailModal.jsx
  src/utils/fileUtils.ts
Labels: bug, enhancement

#28 Update: packages
  package-lock.json
  package.json
Labels: bug, enhancement, Refactoring

#29 Update: package
  package-lock.json
  package.json
Labels: bug, enhancement, Refactoring

#36 Update#20/connect api
  src/app/api/upload/route.ts
  src/app/error.tsx
  src/app/files/FilesMain.tsx
  src/app/files/detail/DetailMain.tsx
  src/app/files/detail/page.tsx
  src/app/files/detail2/Detail2Main.tsx
  src/app/files/detail2/page.tsx
  src/app/files/page.tsx
  src/app/folders/FolderMain.tsx
  src/app/folders/page.tsx
  src/app/not-found.tsx
  src/app/test/page.jsx
  src/components/screen/AIChat.tsx
  src/components/screen/DocList.tsx
  src/components/screen/DocumentViewer.tsx
  src/components/ui/ActionButton.tsx
  src/components/ui/ChatBubble.tsx
  src/components/ui/ChatbotModal.tsx
  src/components/ui/DetailModal.jsx
  src/components/ui/DetailModal.tsx
  src/components/ui/DocList.jsx
  src/components/ui/DropdownItem.tsx
  src/components/ui/DropdownMenu.tsx
  src/components/ui/EmptyStateMessage.tsx
  src/components/ui/FileHandleMenuBar.tsx
  src/components/ui/FolderActionButtons.tsx
  src/components/ui/FolderCard.tsx
  src/components/ui/FolderMenuBar.tsx
  src/components/ui/RenameFolderPopup.tsx
  src/components/ui/SearchBar.tsx
  src/components/ui/TagBadge.tsx
  src/test.txt
  src/utils/fileUtils.ts
Labels: enhancement, feat, Refactoring

#35 Feat: add userdetail file #23
  src/app/userdetail/page.tsx
Labels: enhancement, feat

#38 Deploy #3
  src/app/api/upload/route.ts
  src/app/error.tsx
  src/app/files/FilesMain.tsx
  src/app/files/detail/DetailMain.tsx
  src/app/files/detail/page.tsx
  src/app/files/detail2/Detail2Main.tsx
  src/app/files/detail2/page.tsx
  src/app/files/page.tsx
  src/app/folders/FolderMain.tsx
  src/app/folders/page.tsx
  src/app/not-found.tsx
  src/app/test/page.jsx
  src/app/userdetail/page.tsx
  src/components/screen/AIChat.tsx
  src/components/screen/DocList.jsx
  src/components/screen/DocList.tsx
  src/components/screen/DocumentViewer.tsx
  src/components/ui/ActionButton.tsx
  src/components/ui/ChatBubble.tsx
  src/components/ui/ChatbotModal.tsx
  src/components/ui/DetailModal.jsx
  src/components/ui/DetailModal.tsx
  src/components/ui/DropdownItem.tsx
  src/components/ui/DropdownMenu.tsx
  src/components/ui/EmptyStateMessage.tsx
  src/components/ui/FileHandleMenuBar.jsx
  src/components/ui/FileHandleMenuBar.tsx
  src/components/ui/FolderActionButtons.tsx
  src/components/ui/FolderCard.tsx
  src/components/ui/FolderMenuBar.tsx
  src/components/ui/RenameFolderPopup.tsx
  src/components/ui/SearchBar.tsx
  src/components/ui/TagBadge.tsx
  src/test.txt
  src/utils/fileUtils.ts
Labels: bug, enhancement, feat, Refactoring

#39 Update#20/connect api
  src/app/files/detail/DetailMain.tsx
  src/app/folders/FolderMain.tsx
  src/components/screen/DocumentViewer.tsx
  src/components/screen/MarkdownPreview.tsx
  src/components/ui/CreateFolderPopup.tsx
  src/components/ui/FileHandleMenuBar.tsx
  src/services/folderService.ts
Labels: enhancement, feat, Refactoring

#40 Almost done!
  src/app/files/detail/DetailMain.tsx
  src/app/folders/FolderMain.tsx
  src/components/screen/DocumentViewer.tsx
  src/components/screen/MarkdownPreview.tsx
  src/components/ui/CreateFolderPopup.tsx
  src/components/ui/FileHandleMenuBar.tsx
  src/services/folderService.ts
Labels: enhancement, feat, Refactoring

#42 Update#20/connect api
  src/app/files/detail/DetailMain.tsx
  src/components/screen/AIChat.tsx
Labels: enhancement, feat, Refactoring

#43 Sub-Final
  src/app/files/detail/DetailMain.tsx
  src/components/screen/AIChat.tsx
Labels: enhancement

#47 ALL DONE
  src/app/api/chat/route.ts
  src/app/files/detail/DetailMain.tsx
  src/components/screen/AIChat.tsx
Labels: enhancement, Refactoring
